# Generated by Django 5.1.1 on 2024-11-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_personala', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='emial',
            new_name='email',
        ),
    ]
